title: SEHYEON PARK
logo: /assets/img/logo.jpg
email: bboxeeee@koreatech.ac.kr
description: 한국기술교육대학교 컴퓨터공학부 3학년
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto

# Analytics
analytics:
  provider               : "google-gtag"
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-DCR3RLSF9X"
    anonymize_ip         : # true, false (default)

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/bboxeeee
  - name: Velog
    icon: <i class="fa-brands fa-blogger"></i>
    link: https://velog.io/@bboxeee
  - name: NAVER Blog
    icon: <i class="fa-brands fa-blogger"></i>
    link: https://blog.naver.com/noeyhesx
  - name: Instagram
    icon: <i class="fa-brands fa-square-instagram"></i>
    link: https://www.instagram.com/_sxhxun

navigation:
  - name: Baekjoon
    link: ./baekjoon
  - name: Projects
    link: ./projects
  - name: About
    link: ./about-page.html
 
