title: SEHYEON PARK
logo: /assets/img/logo.jpg
email: noeyhesx@naver.com
description: 한국기술교육대학교 컴퓨터공학부 3학년
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/bboxeeee
  - name: Velog
    icon: <i class="fa-brands fa-blogger"></i>
    link: https://velog.io/@bboxeee
  - name: NAVER Blog
    icon: <i class="fa-brands fa-blogger"></i>
    link: https://blog.naver.com/noeyhesx
  - name: Instagram
    icon: <i class="fa-brands fa-square-instagram"></i>
    link: https://www.instagram.com/_sxhxun

navigation:
  - name: Blog
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: About
    link: ./another-page.html
